name: Code Quality checks

on:
  pull_request:
    branches:
      - dev
      - staging

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v3
        with:
          version: 10.12.4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Format Check
        id: format-check
        run: pnpm run format:check
        continue-on-error: true

      - name: Format Code (if needed)
        if: steps.format-check.outcome == 'failure'
        run: pnpm run format

      - name: Commit changes
        if: steps.format-check.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: apply formatting changes'
          branch: ${{ github.head_ref }}
